# Generated by Django 3.2.5 on 2021-07-22 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dozen', models.CharField(max_length=5, verbose_name='Primeia dezena')),
                ('second_dozen', models.CharField(max_length=5, verbose_name='Segunda dezena')),
                ('third_dozen', models.CharField(max_length=5, verbose_name='Terceira dezena')),
                ('fourth_dozen', models.CharField(max_length=5, verbose_name='Quarta dezena')),
                ('fifth_dozen', models.CharField(max_length=5, verbose_name='Quinta dezena')),
                ('sixth_dozen', models.CharField(max_length=5, verbose_name='Sexta dezena')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da jogada')),
            ],
            options={
                'verbose_name': 'Jogada',
                'verbose_name_plural': 'Jogadas',
            },
        ),
    ]
