# Generated by Django 3.2.5 on 2021-07-20 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_plays_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plays',
            options={'verbose_name': 'Jogada', 'verbose_name_plural': 'Jogadas'},
        ),
        migrations.AddField(
            model_name='plays',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da jogada'),
        ),
    ]
